### ISSUE TITLE
PerspectiveCamera usage.

### ISSUE THREAD

**Issue by vkornii** [mattdesl/lwjgl-basics#6]
How can I draw trails with perspective camera?
I tried to add next lines to SwipeTriStrip draw() method : 

```
       Vector2 point = tristrip.get(i);
            Vector2 tc = texcoord.get(i);
           point3.set(point.x, point.y, 0f);
            cam.unproject(point3);
            tc3.set(tc, 0f);
            cam.unproject(tc3);
            gl20.color(color.r, color.g, color.b, color.a);
            gl20.texCoord(tc3.x, tc3.z);
            gl20.vertex(point3.x, point3.y, point3.z);
```

But it not working.
Thanks in advance

**Comment by mattdesl** [comment]
Where are you getting the PerapectiveCamera class from? Usually you use camera.project() to go from world space to screen space. 

That function is more useful for software rendering and hit testing, though. 

If you are using GL, then you would pass the "combined" camera matrix to the vertex shader as a uniform, and do something like:

gl_Position = mvp_matrix \* vec4(a_position.xyz, 1.0);

If you're using LibGDX, you should just pass the combined matrix to it the ImmediateModeRenderer. Then, you can pass 3D points to vertex() and it will transform them in the shader for you.
