### ISSUE TITLE
For lwjgl-basics tutorial, Shader 6

### ISSUE THREAD

**Issue by gannonprudhomme** [mattdesl/lwjgl-basics#7]
Hey Matt, the Java & LWJGL link Shader 6 for Normal Mapping just links to the same URL of the tutorial when it's clicked on. Would love if you added the source code. Thanks. Edit: Also, I'm trying not to use libgdx, that's why I ask :).

**Comment by mattdesl** [comment]
Thanks, updated the link
https://github.com/mattdesl/lwjgl-basics/blob/master/test/mdesl/test/shadertut/ShaderLesson6.java
